### ISSUE TITLE
Pytest metrics gives Type Error at the teardown (pytest_runtest_teardown)

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-metrics#1]
Refer error logs below:    

def pytest_runtest_teardown(item, nextitem):

        _test_end_time = time.time()

        global _test_name
        _test_name = item.name

        global _duration
>       _duration = _test_end_time - _test_start_time
E       TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

C:\Program Files (x86)\Python37-32\lib\site-packages\pytest_metrics-0.2-py3.7.egg\pytest_metrics\plugin.py:133: TypeError

![image](https://user-images.githubusercontent.com/12759282/75031100-84b88180-54cb-11ea-928b-ee64a5460821.png)

This results in an unexpected additional failure at the end of execution.

**Comment by parwalrahul** [comment]
Hi Shiva, Did you get a chance to look into this issue ?

**Comment by adiralashiva8** [comment]
> Hi Shiva, Did you get a chance to look into this issue ?

Sorry, I overlooked into issues, Will take a look into it

**Comment by parwalrahul** [comment]
Observation : This occurs when you try to run a test which is skipped using pytest hooks
