### ISSUE TITLE
Need One time logo set facility in pytest metrics

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-metrics#2]
**Proposed Enhancement:**

The current implementation of the pytest metrics facilitates the user to provide the URL/Path of the logo as a parameter while executing the tests.
This is an redundant activity considering that users would always love to have their own branding instead of manually specifying each time.

If we could have some global facility / location where user could one time update the image or image url then it would be a big effort saver.

**Comment by adiralashiva8** [comment]
This can be achieved by simple work around as follows

**Step 1:** Edit `plugin.py` 

Can be found under following location
```C:\Users\<user-name>\AppData\Local\Programs\Python\Python37\Lib\site-packages\pytest_metrics\plugin.py```

**Step 2:** Modify `--mlogo` default value (line no 50)

```default="https://my-company-logo.png"```

**Step 3:** Save changes

**Note**: This change applicable in local machine

Now default logo of `pytest-metrics` will be logo metioned in **Step 2**

**Comment by parwalrahul** [comment]
Thanks. This is working. We can close this issue.
