### ISSUE TITLE
Show all results option must also be available in pytest-metrics

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-metrics#3]
![image](https://user-images.githubusercontent.com/12759282/76162363-0e6e7d00-6163-11ea-9ddd-a060941c9646.png)

This option becomes very useful in scenarios where test count goes above 100 and user wants to export results.

**Comment by adiralashiva8** [comment]
Functionality: By default `Jquery Datatable` will export all the results irrespective of show X entries selection, user can export entire results without `All` option

I feel `All` option will make metrics report view bit congested. Any specific requirement for `All` option so I will work on that

**Comment by parwalrahul** [comment]
We can close this issue but is there any way we can reflect this on the UI (maybe on Hover over the download button for csv and xlx).

**Comment by parwalrahul** [comment]
I guess the user might feel that it only exports the viewable data. (this is based on my personal opinion actually)

**Comment by adiralashiva8** [comment]
We dont use `All` in robotframework related projects. Will keep it open, If any other user raise this concern will definatley implement as suggested

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/pytest-metrics/commit/cb17f2057f777d4f4f7ecc9269899f14fd341f10

Sample v4 report - https://pytest-metrics.netlify.com/
