### ISSUE TITLE
pytest-metrics report not getting saved with the datetime stamp in version 0.3

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-metrics#4]
The datetime stamp helps to keep a natural archive of the test reports. Very useful for teams doing rapid test execution.

**Comment by parwalrahul** [comment]
Old metrics file gets replaced with latest metrics file due to this.

**Comment by adiralashiva8** [comment]
In `v0.3` added new argument `--mtimestamp` whose default value is `False`. Users can enable feature by `--mtimestamp=True` option

I took `robotframework` as reference where by default append timestamp to report if `False`

**Comment by parwalrahul** [comment]
Can we use uniform flag name in pytest-metrics and pytest-live logs to maintain uniformity ?
It would be typical for user to remember both flags all the time as they are not totally identical.

Current Implementation : 
Pytest-metrics : mtimestamp
Pytest-Live: livetimestamp

Suggested Implementation:
1. Pytest-metrics : timestamp && Pytest-Live: timestamp (Both using same flag, Not sure about it's feasability though).
2. Pytest-metrics : ltimestamp && Pytest-Live: mtimestamp (Both flag having uniform name <package case : l or m>timestamp).

**Comment by parwalrahul** [comment]
Also, we should can think of updating documentation as suggested in the pytest-live to remove any ambiguity for initial user.
Any software is as good as it's documentation.

**Comment by adiralashiva8** [comment]
> Can we use uniform flag name in pytest-metrics and pytest-live logs to maintain uniformity ?
> It would be typical for user to remember both flags all the time as they are not totally identical.
> 
> Current Implementation :
> Pytest-metrics : mtimestamp
> Pytest-Live: livetimestamp
> 
> Suggested Implementation:
> 
> 1. Pytest-metrics : timestamp && Pytest-Live: timestamp (Both using same flag, Not sure about it's feasability though).
> 2. Pytest-metrics : ltimestamp && Pytest-Live: mtimestamp (Both flag having uniform name timestamp).

There will be a case where I want to append timestamp to metrics report but not for live, in this case using same arguments causes issue. So I have used different argument naming

Regarding documentation: I have added single line comment, will improve it, thank you

**Comment by parwalrahul** [comment]
Agreed. Closing this issue.
